### ISSUE TITLE
 lock/wait  msg on the exit

### ISSUE THREAD

**Issue by quickwritereader** [SX-Aurora/veda#18]
we have java project(dl4j) that calls cpp library with veda.
I am facing strange behaviour with Veda. I dont know if I'm using veda incorrectly or its something else.

so each time on exit I'm getting this (annoying lock/wait with below messages):
[VH] [TID 3480243] ERROR: wait_req_ack() timeout waiting for ACK req=1604
[VH] [TID 3480243] ERROR: close() child sent no ACK to EXIT. Killing it.

plus when I ran my inference more , I am getting error for the method call which works just fine for one inference session.
```
[VE] ERROR: sigactionHandler() Interrupt signal 11 received
0x600fffe00000
0x60001004cf40 -> (null)
0x600c01583b60 -> __vthr$_pcall_va
[VH] [TID 3611133] ERROR: unpack_call_result() VE exception 11
@$+U?^\s?(*f@xϾ?vA]
[VH] [TID 3611133] ERROR: _progress_nolock() Internal error on executing a command(-4)
[VEDA_ERROR_VEO_COMMAND_EXCEPTION] /home/qwr/veda/src/veda/Context.cpp (435)

```

I'm using the veda this way: for now I integrated your vednn library through veda, so it has few ops support
java->javacpp-> nd4jcpp+veda-> device vednn lib

```


Veda handle cpp class {
     function,
     module, 
     ctx

}

```
```
Singleton Veda{
   list<veda_handle> ;
  //for now I'm using one device
  init(){ 
  init and load libs per device, 
 also I pop
vedaCtxPopCurrent;
//this way I'm solving vedaExit problem that I had because of thread local std::list
 }
exit() { vedaExit;}

}
```

how I'm callng (for now I'm calling it using 0th device with the context that was created in OMP mode):
```
    vedaDevicePrimaryCtxRetain(&ctx, device);
    vedaCtxPushCurrent(ctx);

    veda Mem calls..
   veda Launch

   sync

   vedaCtxPopCurrent(&ctx);
```

**Comment by quickwritereader** [comment]
I will try install the latest veda from the source to see if I get the same errors.

**Comment by quickwritereader** [comment]
here is my relevant source files.
[veda_helper.h](https://github.com/quickwritereader/deeplearning4j/blob/master/libnd4j/include/ops/declarable/platform/vednn/veda_helper.h)

[veda_vednn-device](https://github.com/quickwritereader/deeplearning4j/blob/master/libnd4j/include/ops/declarable/platform/vednn/veda_vednn.vcpp)

[veda vednn conv2d relevant lines](https://github.com/quickwritereader/deeplearning4j/blob/master/libnd4j/include/ops/declarable/platform/vednn/conv2d.cpp#L221-L257)
there I call sync after launch , but I'm getting the same error if I call it at the end as well

**Comment by mergian** [comment]
Hey

Signal 11 means a segfault happened in your VE code.

1. you can try to compile your VE code with debug enabled to see if you get a stack trace reported.

2. you are using ```bool``` in your ```vedaVednn...``` calls. These are 4B on VE and usually only 1B on the host so I assume the parameters that get passed onto to the function on VE side can be misaligned resulting in random behavior. Please check with printf if all the arguments you pass to the kernels have the same signature on host and device. There are no checks between what you pass as arguments in VEDA and what the VE code expects because of the extern "C" binding.

**Comment by quickwritereader** [comment]
thanks Nicolas, I will recheck them and use width based types
what is your idea on  getting lock/wait on exit?

**Comment by quickwritereader** [comment]
I see the latest source is using your illyrian project. my pip installed cmake cant see it thought I installed them using -m pip .
so I assume the latest changes will not help on this I better switch back  to the old one (HEAD~1) and try to fix those possible issues to see if it helps. I'm using launchKernel instead of Ex version because of I'm getting older version using yum

**Comment by mergian** [comment]
**"the lock/wait on exit?"**:
I think it should work, but as said in the other thread it's not necessary to call vedaExit except you want to free the devices at runtime, i.e. when you only need them in a specific section of your application.

**"Illyrian"**:
you first need to install it using ```python3 -m pip install illyrian``` and then create your build folder like ```illyrian cmake ...```. Alternatively you can do ```cmake -DCMAKE_MODULE_PATH=/path/to/illyrian/cmake ...```. The command is just a convenience wrapper.

**Comment by quickwritereader** [comment]
yes like on exit I'm getting these messages:
[VH] [TID 3480243] ERROR: wait_req_ack() timeout waiting for ACK req=1604
[VH] [TID 3480243] ERROR: close() child sent no ACK to EXIT. Killing it.
I try to remove vedaExit to see if those disappear

**Comment by mergian** [comment]
They might disappear but they indicate that something is wrong with your application. They indicate that the VE process has died and that the host is waiting for a life sign. You need to fix the segfault first, then these will disappear automatically.

**Comment by quickwritereader** [comment]
I believe, indeed it was type mismatch which led such random behaviour.  I was not able to spot that blunder yesterday as it was working fine for one session(110 conv calls).
thanks you saved my time.

**Comment by quickwritereader** [comment]
commented VedaExit(), but still getting
```
[VH] [TID 3073281] ERROR: wait_req_ack() timeout waiting for ACK req=158420
[VH] [TID 3073281] ERROR: close() child sent no ACK to EXIT. Killing it.
```

**Comment by quickwritereader** [comment]
https://gist.githubusercontent.com/quickwritereader/1cc95b3044f254468f399038546b488b/raw/055498c62fac21da4422484ac1e29bfa0ee43d40/VEO_LOG_DEBUG.tracesx.txt

**Comment by efocht** [comment]
Is your VE process still crashing? If yes, please try running the aveorun binary under a debugger. Like here: https://sx-aurora.github.io/posts/aveo-debugging/ (VE side debugging). You must find where and why your VE kernel is crashing. VEDA waits for it to send an ACK, but if it has crashed, that ACK will never come. This is a problem in your kernel.

**Comment by quickwritereader** [comment]
@efocht random crash ~was due to type width mismatch which I corrected~, 
on exit I 'm getting 
```
[VH] [TID 3375508][TRACE] operator()() [request #1601] reply sendbuff received (cmd=4)...
[VH] [TID 3375508][TRACE] operator()() [request #1601] unpacked
[VH] [TID 3375508][TRACE] callWaitResult() req 1602
[VE] [DEBUG] call_handler() cmd=14
[VE] [DEBUG] call_handler() CALL nregs=1
[VE] [DEBUG] call_handler() no stack, nregs=1
[VE] [DEBUG] call_handler() sending RESULT
[VH] [TID 3375508][TRACE] operator()() [request #1602] reply sendbuff received (cmd=4)...
[VH] [TID 3375508][TRACE] operator()() [request #1602] unpacked
.....
[VH] [TID 3375382][TRACE] exitProc() proc 0x7f3bc0989060
[VH] [TID 3375382][TRACE] close() ctx=0x7f3bc0884250
[VH] [TID 3375382] ERROR: wait_req_ack() timeout waiting for ACK req=1604
[VH] [TID 3375382] ERROR: close() child sent no ACK to EXIT. Killing it.
Sending SIGKILL to child[VH] [TID 3375382][DEBUG] exitProc() erasing proc 7f3bc0989060
[VH] [TID 3375382][TRACE] _getProcIdentifierNolock() proc 0x7f3bc0989060 identifier = 0
```
it seems, TID differs

it could be related to java and its threading/ gc thread

**Comment by quickwritereader** [comment]
I wrote thread_local scoped intializer to overcome that problem.
it seems it works but I am not sure what problems it might cause.
```

struct ThreadLocalScopVeda {
  bool isOk =false;

  ThreadLocalScopVeda()=default;

  VEDA_STATUS initVeda(){
      auto status = VEDA_CALL(vedaInit(0));
      if(status) isOk = true; 
      return status;
  }

  ~ThreadLocalScopVeda (){
    if(isOk){
      sd_printf("%s %d\n",__FILE__, __LINE__);
      VEDA_CALL(vedaExit()); 
    }
  }

};

thread_local ThreadLocalScopVeda scopedVeda;

VEDA::VEDA(const char* library_name){
    int devcnt = 0;
    auto status = scopedVeda.initVeda();
    if (status) {
      status = VEDA_CALL(vedaDeviceGetCount(&devcnt));
    }
   //codes related
    const char* dir_name = sd::Environment::getInstance().getVedaDeviceDir();
    int use = (devcnt > MAX_DEVICE_USAGE) ? MAX_DEVICE_USAGE : devcnt;
    sd_printf("Veda devices: available %d \t will be in use %d\n", devcnt, use);
    for (int i = 0; i < use; i++) {
      VEDAdevice device;
      vedaDeviceGet(&device, i);
      VEDA_HANDLE v(library_name, device, dir_name);
      ve_handles.emplace_back(std::move(v));
    }
  }
```
this way I can call vedaExit in the same thread in logs ( [VH] [TID] ) where VedaInit called .
```
[VH] [TID 1270025][TRACE] exitProc() proc 0x7fb1cc96c390
[VH] [TID 1270025][TRACE] close() ctx=0x7fb1cc8a8820
[VE] [DEBUG] exit_handler() up=0x601000f45480 has received the EXIT command
[VH] [TID 1270025][TRACE] close() entering waitpid(1270174)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.513 s
[INFO] Finished at: 2022-04-07T00:38:13+09:00
[INFO] ------------------------------------------------------------------------
[VH] [TID 1270025][DEBUG] close() waitpid(1270174) returned status=0
[VH] [TID 1270025][DEBUG] exitProc() erasing proc 7fb1cc96c390
[VH] [TID 1270025][TRACE] _getProcIdentifierNolock() proc 0x7fb1cc96c390 identifier = 0
[VH] [TID 1269876][DEBUG] _cleanup_procs() proc destructor: proc pointer is NULL!
```

**Comment by quickwritereader** [comment]
it seems I started getting sigsegv randomly , again
```
[VE] ERROR: sigactionHandler() Interrupt signal 11 received
0x600fffe00000
0x60001004cf40 -> (null)
0x600c01583b60 -> __vthr$_pcall_va
[VH] [TID 1199317] ERROR: unpack_call_result() VE exception 11
]
[VH] [TID 1199317] ERROR: _progress_nolock() Internal error on executing a command(-4)
[VEDA_ERROR_VEO_COMMAND_EXCEPTION] /home/qwr/veda/src/veda/Context.cpp (435)
```
