### ISSUE TITLE
understanding the vedaMemcpyHtoDAsync sync behaviour and veo_async_write_mem poor performance

### ISSUE THREAD

**Issue by quickwritereader** [SX-Aurora/veda#19]
I'm using one device +one stream OMP mode:
My Veda codes almost correspond below lines:
```
//once: vedaCtxCreate(&ctx, VEDA_CONTEXT_MODE_OMP, 0)

vedaDevicePrimaryCtxRetain(&ctx, device);
vedaCtxPushCurrent(ctx);
vedaMemAllocAsync
vedaMemcpyHtoDAsync
...
call kernel
 vedaCtxPopCurrent(&ctx);
```
I keep Veda calls async and synchronize them when I need them inside the CPU operations.

to my surprise, my async Veda operations took more time than I expected, as it was synchronizing inside (vedaMemcpyHtoDAsync).

**Comment by mergian** [comment]
Yes VEDA might need to sync before any memcopy. The reason is that Malloc returns the raw pointer to the host asynchronously. In case it has not been returned to the host yet, VEDA synchronizes to wait for the raw pointer.

In your example you allocate and memcpy immediately which triggers this behavior. If you have other calls in between a sync might not be necessary.

**Comment by quickwritereader** [comment]
I see, but what about the poor performance of the veo_async_write_mem
for size 22257792 it took 4ms in my logs

**Comment by quickwritereader** [comment]
```
#include <chrono>
#define NOW() std::chrono::high_resolution_clock::now()
#define time(start, end) (std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count()/1000000.0)
```

```
void Context::memcpyH2D(VEDAdeviceptr dst, const void* src, const size_t bytes, VEDAstream _stream) {
	if(!dst || !src)
		VEDA_THROW(VEDA_ERROR_INVALID_VALUE);
auto t0 = NOW();
	auto res	= getPtr(dst);
	auto ptr	= res.ptr;	ASSERT(ptr);
	auto size	= res.size;	ASSERT(size);
	if((bytes + VEDA_GET_OFFSET(dst)) > size)
		VEDA_THROW(VEDA_ERROR_OUT_OF_BOUNDS);
auto t1 = NOW();
	auto& s		= stream(_stream);
	auto t2 = NOW();
	uint64_t req	= CREQ(veo_async_write_mem(s.ctx, (veo_ptr)ptr, src, bytes));
auto t3 = NOW();
	LOCK(s.mutex);
	auto t4 = NOW();
	s.calls.emplace_back(req, false, (uint64_t*)0);
	auto t5 = NOW();
	printf("%f %f %f %f %f \n",time(t0,t1), time(t1,t2), time(t2,t3), time(t3, t4), time(t4, t5));
}

```
```
VEDAresult vedaMemcpyHtoDAsync(VEDAdeviceptr dstDevice, const void* srcHost, size_t ByteCount, VEDAstream hStream) {
    auto start = NOW();
	printf("%s %d \n", __FILE__, __LINE__);
	GUARDED(
		auto& ctx = veda::Devices::get(dstDevice).ctx();
		L_TRACE("[ve:%i] vedaMemcpyHtoDAsync(%p, %p, %llu, %i)", ctx.device().vedaId(), dstDevice, srcHost, ByteCount, hStream);
		ctx.memcpyH2D(dstDevice, srcHost, ByteCount, hStream);
			 auto end = NOW();
	printf("%s %d %d %f ms\n", __FILE__, __LINE__, (int)ByteCount, time(start,end));
	)

}
```

60.403471 0.000054 4.852972 0.000160 0.000033
src/veda/veda_mem.cpp 498 22257792 65.270248 ms 

0.242248 0.000023 0.021660 0.000030 0.000033
src/veda/veda_mem.cpp 498 73728 0.271374 ms
 
0.024647 0.000022 2.039926 0.000109 0.000023
src/veda/veda_mem.cpp 498 11075584 2.072956 ms

the 3rd is veo_async_write_mem, and it takes 4ms and 2ms .

I would like to note that I have 100-1000 calls. so every ms/us matters

**Comment by mergian** [comment]
You need to ask that question in the AVEO GitHub. Don’t know about the internals of AVEO memcpy.
