### ISSUE TITLE
Wrong MPI version found by injection script

### ISSUE THREAD

**Issue by Severin-S** [SX-Aurora/veda#4]
Hi,
I noticed that with multiple MPI versions installed, veda doesn't always selects the newest version when using the injection.
With versions 1.3.0, 2.0.0, 2.2.0, 2.3.0, 2.5.0, 2.7.0 and 2.10.0 installed this leads to 2.7.0 being selected. It would be nice if veda would either select the newest MPI version, or, even better, use the MPI version which is in PATH. (At RWTH Aachen we use a module system on the aurora to switch between multiple compiler/MPI versions which would be nice to be considered by veda)

Best regards,
Severin

**Comment by mergian** [comment]
Hey Severin,

The reason for this problem is, that CMake introduced "NATURAL" sorting in 3.18 ( https://cmake.org/cmake/help/v3.18/command/list.html ) which would have the correct behavior. However, most people have older versions of CMake installed because of their distribution, so we have not been using NATUARL sorting yet. Let me think how to improve this to be compatible with older CMakes and still have the correct behavior.

Fetching the MPI version from the PATH (and I assume LD_LIBRARY_PATH) env vars should work.

I'll put these two on the TODO list.

Best

**Comment by mergian** [comment]
Hey Severin,

I just pushed a bugfix to the master branch. Please try if this fixes your problem.

## With MPI in PATH env var
```
PATH=$PATH:/opt/nec/ve/mpi/2.5.0/bin cmake -C /usr/local/veda/cmake/InjectVE.cmake ..

loading initial cache file /usr/local/veda/cmake/InjectVE.cmake
-- The C compiler identification is NCC 3.1.20
-- The CXX compiler identification is NCC 3.1.20
-- The Fortran compiler identification is NCC 3.1.20
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP_Fortran: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found NLC 2.1.0
-- Using NLC 2.1.0 ASL OpenMP Shared INT32
-- Using NLC 2.1.0 BLAS OpenMP Shared INT32
-- Found MPI 2.5.0
-- Using NLC 2.1.0 LAPACK Shared
-- Configuring done
-- Generating done
-- Build files have been written to: /veda/example/cmake_find/build
```

## With fixed version lookup
```
cmake -C /usr/local/veda/cmake/InjectVE.cmake ..

loading initial cache file /usr/local/veda/cmake/InjectVE.cmake
-- The C compiler identification is NCC 3.1.20
-- The CXX compiler identification is NCC 3.1.20
-- The Fortran compiler identification is NCC 3.1.20
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP_Fortran: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found NLC 2.1.0
-- Using NLC 2.1.0 ASL OpenMP Shared INT32
-- Using NLC 2.1.0 BLAS OpenMP Shared INT32
-- Found MPI 2.10.0
-- Using NLC 2.1.0 LAPACK Shared
-- Configuring done
-- Generating done
-- Build files have been written to: /veda/example/cmake_find/build
```

**Comment by Severin-S** [comment]
Yes, now everything works as expected, thank you!
