### ISSUE TITLE
MPI_<LANG>_COMPILER not set correctly

### ISSUE THREAD

**Issue by Severin-S** [SX-Aurora/veda#5]
Hi,

when using your injection the MPI_<LANG>_COMPILER variables are not set to a valid MPI Compiler.

For instance
```cmake
CMAKE_MINIMUM_REQUIRED(VERSION 3.9)

PROJECT(TEST C CXX)

FIND_PACKAGE(MPI REQUIRED)

message(${MPI_C_COMPILER})
```
returns `/opt/nec/ve/ncc/3.0.8/bin/ncc/mpincc` as path for the MPI C Compiler.

Best regards,
Severin

**Comment by mergian** [comment]
Hey Severin,

it seems wrongly used the path to the compiler instead of using MPI_PATH. Just pushed a commit that fixes that issue.

## ccmake output
```
 MPI_CXX_COMPILER                 /opt/nec/ve/mpi/2.10.0/bin/mpinc++
 MPI_CXX_INCLUDE_DIRS             /opt/nec/ve/mpi/2.10.0/include
 MPI_C_COMPILER                   /opt/nec/ve/mpi/2.10.0/bin/mpincc
 MPI_C_INCLUDE_DIRS               /opt/nec/ve/mpi/2.10.0/include
```

Best

**Comment by Severin-S** [comment]
Great, thanks!
