### ISSUE TITLE
fatal error: vera_enums.h: No such file or directory 

### ISSUE THREAD

**Issue by ftpronk** [SX-Aurora/veda#7]
Some header files seem to be missing when compiling code using vera.h

My CMake compilation output is:
```
/usr/local/ve/veda-0.9.5/include/vera.h:4:24: fatal error: vera_enums.h: No such file or directory  
 #include "vera_enums.h"
```

As a side note, when searching the aurora system (and the github repository), I can't find the next file included in `vera.h` either:
- `vera_types.h`

**Comment by mergian** [comment]
Thanks for reporting.

Seems these two files are missing in the CMake INSTALL instruction ( https://github.com/SX-Aurora/veda/blob/87ed26b03c9c1c6c006612ce38e007fb7b359c23/CMakeLists.txt#L149 )
and therefore don't get included into the RPM file. Will fix it and generate a new RPM v0.9.5.1.
